package com.model;

/**
 * TTouzhi generated by MyEclipse Persistence Tools
 */

public class TTouzhi implements java.io.Serializable
{

	// Fields

	private int touzhiId;

	private String touzhiShijian;

	private Integer touzhiJine;

	private String touzhiHuankuanshijian;

	private Integer userId;

	// Constructors

	/** default constructor */
	public TTouzhi()
	{
	}

	/** full constructor */
	public TTouzhi(String touzhiShijian, Integer touzhiJine,
			String touzhiHuanhuan, Integer userId)
	{
		this.touzhiShijian = touzhiShijian;
		this.touzhiJine = touzhiJine;
		this.userId = userId;
	}

	// Property accessors


	public String getTouzhiShijian()
	{
		return this.touzhiShijian;
	}

	public void setTouzhiShijian(String touzhiShijian)
	{
		this.touzhiShijian = touzhiShijian;
	}

	public Integer getTouzhiJine()
	{
		return this.touzhiJine;
	}

	public void setTouzhiJine(Integer touzhiJine)
	{
		this.touzhiJine = touzhiJine;
	}


	public String getTouzhiHuankuanshijian()
	{
		return touzhiHuankuanshijian;
	}

	public void setTouzhiHuankuanshijian(String touzhiHuankuanshijian)
	{
		this.touzhiHuankuanshijian = touzhiHuankuanshijian;
	}

	public Integer getUserId()
	{
		return this.userId;
	}

	public void setUserId(Integer userId)
	{
		this.userId = userId;
	}

	public int getTouzhiId()
	{
		return touzhiId;
	}

	public void setTouzhiId(int touzhiId)
	{
		this.touzhiId = touzhiId;
	}

}