package com.model;

/**
 * TXiaofei generated by MyEclipse Persistence Tools
 */

public class TXiaofei implements java.io.Serializable
{

	// Fields

	private Integer xiaofeiId;

	private String xiaofeiShijian;

	private String xiaofeiDidian;

	private Integer xiaofeiJine;

	private String xiaofeiBeizhu;

	private int userId;

	// Constructors

	/** default constructor */
	public TXiaofei()
	{
	}

	/** minimal constructor */
	public TXiaofei(Integer xiaofeiId)
	{
		this.xiaofeiId = xiaofeiId;
	}

	/** full constructor */
	public TXiaofei(Integer xiaofeiId, String xiaofeiShijian,
			String xiaofeiDidian, Integer xiaofeiJine, String xiaofeiBeizhu,
			String userId)
	{
		this.xiaofeiId = xiaofeiId;
		this.xiaofeiShijian = xiaofeiShijian;
		this.xiaofeiDidian = xiaofeiDidian;
		this.xiaofeiJine = xiaofeiJine;
		this.xiaofeiBeizhu = xiaofeiBeizhu;
	}

	// Property accessors

	public Integer getXiaofeiId()
	{
		return this.xiaofeiId;
	}

	public void setXiaofeiId(Integer xiaofeiId)
	{
		this.xiaofeiId = xiaofeiId;
	}

	public String getXiaofeiShijian()
	{
		return this.xiaofeiShijian;
	}

	public void setXiaofeiShijian(String xiaofeiShijian)
	{
		this.xiaofeiShijian = xiaofeiShijian;
	}

	public String getXiaofeiDidian()
	{
		return this.xiaofeiDidian;
	}

	public void setXiaofeiDidian(String xiaofeiDidian)
	{
		this.xiaofeiDidian = xiaofeiDidian;
	}

	public Integer getXiaofeiJine()
	{
		return this.xiaofeiJine;
	}

	public void setXiaofeiJine(Integer xiaofeiJine)
	{
		this.xiaofeiJine = xiaofeiJine;
	}

	public String getXiaofeiBeizhu()
	{
		return this.xiaofeiBeizhu;
	}

	public void setXiaofeiBeizhu(String xiaofeiBeizhu)
	{
		this.xiaofeiBeizhu = xiaofeiBeizhu;
	}

	public int getUserId()
	{
		return userId;
	}

	public void setUserId(int userId)
	{
		this.userId = userId;
	}


}